### ISSUE TITLE
A problem in many binary search implementations

### ISSUE THREAD

**Issue by stackcats** [egonSchiele/grokking_algorithms#92]
The problem is in the assignment 

    mid = (low + high) / 2

It can lead to overflow in some language

**Comment by ajh1143** [comment]
Good to know, which language/languages can this be an issue?

**Comment by stackcats** [comment]
C/C++, Java, etc

**Comment by tiendq** [comment]
> C/C++, Java, etc

Is there any example?

**Comment by enkztw** [comment]
You have to round the mid number down manually

**Comment by mitmih** [comment]
Maybe it's better to use binary shift operator instead of dividing by two and type conversions? I guess most of all programmic languages have it.

I used it, during the grokking [binary search](https://github.com/mitmih/MyOpenPowerShell/blob/master/grokking_algorithms/01_BinarySearch.psm1) algorythm:

```PowerShell
$mid = ($low + $high) -shr 1
(0 + 5) -shr 1  # 2, ok
(0 + 7) -shr 1  # 3, ok
```

There is a problem with the conversion from float to integer, for example, PoSh round a float to nearest even, not to down:

```PowerShell
[int]( (0 + 5) / 2 ) # 2, ok
[int]( (0 + 7) / 2 ) # 4, expect 3
```

**Comment by egonSchiele** [comment]
Hey there, this is a good nuance but not something I would add to this specific book. Closing this issue.
